import { useEffect, useState } from 'react'
import { API_BASE } from '../api.js'

const PROVIDER_LABEL = {
  gemini: 'Google Gemini',
  anthropic: 'Anthropic Claude',
  openai: 'OpenAI',
  'hand-authored-fallback': 'Hand-authored fallback (no LLM key succeeded)',
}

function FamilyCard({ family, config, fidelity }) {
  const checks = fidelity ? Object.entries(fidelity).filter(([k]) => k !== '_overall_pass') : []
  const passed = fidelity?._overall_pass

  return (
    <div className="bg-slate-900 rounded-xl border border-slate-800 p-5">
      <div className="flex items-center justify-between mb-2">
        <h3 className="font-semibold text-slate-100">{family}</h3>
        {fidelity && (
          <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
            passed ? 'bg-emerald-500/20 text-emerald-300' : 'bg-red-500/20 text-red-300'
          }`}>
            fidelity {passed ? 'PASS' : 'FAIL'}
          </span>
        )}
      </div>

      {config && (
        <>
          <div className="text-xs text-slate-500 mb-1">
            Config generated by: <span className="text-teal-400 font-medium">{PROVIDER_LABEL[config.provider] || config.provider}</span>
          </div>
          <blockquote className="text-sm text-slate-300 italic border-l-2 border-teal-700 pl-3 my-3">
            "{config.reasoning}"
          </blockquote>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-xs mb-3">
            <div className="bg-slate-800/60 rounded px-2 py-1.5">
              <div className="text-slate-500">n_instances</div>
              <div className="text-slate-200">{config.n_instances}</div>
            </div>
            <div className="bg-slate-800/60 rounded px-2 py-1.5">
              <div className="text-slate-500">amount shape</div>
              <div className="text-slate-200">{config.amount_distribution}</div>
            </div>
            <div className="bg-slate-800/60 rounded px-2 py-1.5">
              <div className="text-slate-500">burst window</div>
              <div className="text-slate-200">{config.burst_window_steps} steps</div>
            </div>
          </div>
        </>
      )}

      {checks.length > 0 && (
        <details className="text-xs">
          <summary className="cursor-pointer text-slate-500 hover:text-slate-300">fidelity check detail</summary>
          <div className="mt-2 space-y-1">
            {checks.map(([name, result]) => (
              <div key={name} className="flex gap-2">
                <span className={result.pass ? 'text-emerald-400' : 'text-red-400'}>{result.pass ? 'OK' : 'FAIL'}</span>
                <span className="text-slate-500">{name}:</span>
                <span className="text-slate-400 truncate">{result.detail}</span>
              </div>
            ))}
          </div>
        </details>
      )}
    </div>
  )
}

export default function GenerateFidelity() {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    fetch(`${API_BASE}/api/generate`)
      .then((r) => r.json())
      .then(setData)
      .catch((e) => setError(e.message))
  }, [])

  if (error) return <div className="text-red-400">Failed to load: {error}</div>
  if (!data) return <div className="text-slate-400">Loading…</div>

  const families = Object.keys(data.configs_used || {})
  const topFeatures = data.feature_importance ? Object.entries(data.feature_importance).slice(0, 8) : []

  return (
    <div className="space-y-6 max-w-5xl">
      <div className="bg-slate-900 rounded-xl border border-slate-800 p-5">
        <p className="text-sm text-slate-400">
          Attack configs are generated in two stages: an LLM proposes behavioral <i>parameters</i> (amount
          shape, time window, account-graph size) grounded in the attack's real-world mechanism — never
          raw transaction numbers. A deterministic simulator then turns that config into actual PaySim-
          schema rows. Every batch is validated against the real 6.36M-row PaySim backbone (schema, balance
          conservation, per-type value envelope, and family-specific semantic checks) before it's trusted
          enough to train on.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {families.map((family) => (
          <FamilyCard
            key={family}
            family={family}
            config={data.configs_used[family]}
            fidelity={data.fidelity?.[family]}
          />
        ))}
      </div>

      {topFeatures.length > 0 && (
        <div className="bg-slate-900 rounded-xl border border-slate-800 p-5">
          <h3 className="text-sm font-semibold text-slate-200 mb-1">
            What the trained detector actually relies on
          </h3>
          <p className="text-xs text-slate-500 mb-3">
            Feature importances from the trained XGBoost model — graph-derived features (orig_out_degree,
            orig_component_size) sit alongside tabular ones, not as an afterthought.
          </p>
          <div className="space-y-1.5">
            {topFeatures.map(([feat, imp]) => (
              <div key={feat} className="flex items-center gap-3">
                <span className="text-xs text-slate-400 w-56 shrink-0 truncate">{feat}</span>
                <div className="flex-1 bg-slate-800 rounded-full h-2">
                  <div
                    className={`h-2 rounded-full ${feat.includes('degree') || feat.includes('component') || feat.includes('activity') ? 'bg-cyan-500' : 'bg-slate-500'}`}
                    style={{ width: `${Math.min(100, imp * 100 * 3)}%` }}
                  />
                </div>
                <span className="text-xs text-slate-500 w-14 text-right">{(imp * 100).toFixed(1)}%</span>
              </div>
            ))}
          </div>
          <p className="text-xs text-slate-500 mt-3">
            <span className="inline-block w-2 h-2 rounded-full bg-cyan-500 mr-1"></span>
            graph-derived feature
          </p>
        </div>
      )}
    </div>
  )
}
